version: '3.1'
services:
  joomla:
    image: joomla
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: joomla
  joomladb:
    image: mysql:5.7.22
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: joomla
      MYSQL_USER: docker
      MYSQL_PASSWORD: joomla
      MYSQL_DATABASE: mysql
    ports:
      - "3308:3306"
    networks:
      - joomla-network
networks:
  joomla-network:
      driver: bridge